on:
  workflow_dispatch:
jobs:
  workflowcommand:
    runs-on: ubuntu-latest
    steps:
      - name: set API key
        run: echo "API_KEY=12345"
      - name: usgin API key in next step
        run: echo "using the key in the next step $API_KEY"
